### ISSUE TITLE
Per-app filtering of notifications

### ISSUE THREAD

**Issue by Kurtpenter** [holylobster/nuntius-android#5]

**Comment by flyingrub** [comment]
i'm working on it.

**Comment by Kurtpenter** [comment]
Here are some screenshots of the patch from flyingrub

![screen shot 2015-03-25 at 01 16 50](https://cloud.githubusercontent.com/assets/4067807/6815950/fb760ce6-d28c-11e4-8a7c-3664f1ac9b35.png)
![screen shot 2015-03-25 at 01 16 40](https://cloud.githubusercontent.com/assets/4067807/6815951/fb85d6ee-d28c-11e4-8e60-4ffcbfbc8052.png)
![screen shot 2015-03-25 at 01 16 09](https://cloud.githubusercontent.com/assets/4067807/6815952/fb9ba276-d28c-11e4-8e43-8ac9266ecf8e.png)
![screen shot 2015-03-25 at 01 15 58](https://cloud.githubusercontent.com/assets/4067807/6815953/fba1453c-d28c-11e4-9a08-4e7df4cd98ab.png)

**Comment by Kurtpenter** [comment]
The patch from flyingrub is on master ccdd5bce8edcbc54d223b3659a85251e3f97da1f . Please build and test it if you are interested.

**Comment by Hefting** [comment]
Hi there,

This looks good! I like it that you can filter apps which notifications will show up so it won't clutter up everything. Now, I also have a question about this.

The topic says *Per-app filtering of notification*, and nowhere (as far as I can see) is specified whether this should be blacklisting or whitelisting. Maybe I missed something, so I'm honestly curious as to why the decision was made to blacklist apps?

I am wondering this because I use this widget on my Android phone for my lock screen that shows only notification of apps that I whitelist. This I find handy and efficient, since there are a lot of apps (both normal and "hidden") on the Android system I wouldn't want to show up. By hidden I mean that a lot of apps show up that are not in the application launcher, such as Android System or FMRadioService. Blacklisting all of these apps can be tedious and even confusing for newer users, not to mention that it can take a lot of time to filter apps.

I'm not saying that this should be converted to whitelisting apps, but these are just my personal thoughts and like I said: I'm honestly wondering why this decision was made?

Thanks in advance!

**Comment by Kurtpenter** [comment]
Hi!
 We decided for blacklisting and the reason was very simple. In our
workflow we wanted to receive all the notification from our apps... there
were really no app, or very few, we wanted to blacklist.

However we think the blacklisting may be improved and we are thinking about
the following:
1) pre-configured set of "system" apps we may ship pre-blacklisted. If you
want you can remove from the blacklist
2) on each notification you receive on the PC you should be able to easily
blacklist the app forever with a click of your mouse
3) ease the blacklisting on the phone by adding at least a search capability

(Note these are not top priority tasks at the moment.)

What do you think?

Thanks for your feedback! In latest v1.1 you can try the app blacklisting
feature and help us improve it!

Ciao,
Andrea

**Comment by Hefting** [comment]
Hi Andrea,

I see, thanks for explaining! I also tried it in the newer version, looking good!

I can imagine that there aren't a lot of apps that you want to blacklist in your workflow. Let me tell more about mine: I wouldn't be very interested in, let's say, notifications from the Play Store. When there's an update for an application on my phone, I see no point in showing that notification on the desktop. This is because at that moment you're working on your computer and updating the application will not enhance your desktop experience. This would actually distract me. What I am interested in is, let's say, texts and phone calls. With regards to blacklisting I agree that it would be a good approach for this workflow too. I think that indeed all three points would be of a great help, especially number 1 and 2 would make handling it very easy. So, good thinking! :-)

There's still a little concern with regards to some apps making it through this filter and possibly making it confusing. Would this be bad? I don't think so. An example I noticed: Mozilla has Firefox WebApps for both desktop and Android, which seem like normal apps. When I launched one of those, a notification with the Firefox logo showed up. Since Fedora and Ubuntu come with Firefox, the user wouldn't know for sure whether it's coming from the desktop or from the phone. I'm not sure, but I think this also counts for ("hidden") system apps that some phones do have and some don't have: "is it Linux or is it Android?". Like I said: this doesn't have to be a problem. One solution could be that the logo you're showing in the desktop notification would be the Holy Lobster, the user would recognize it, hide it forever and that's it! But maybe you already figured that out.

I would love to help you with your project, because I has some amazing potential! But unfortunately I don't have much time due to my graduation project. So, all I can do is try to help you with my point of view, so I'm sorry for that. :-( Maybe there's still some work to do when I've graduated. But hopefully this is already of little help!

Cheers, Ties Jan

**Comment by Kurtpenter** [comment]
Thank you Ties Jan, don't be sorry! your comments are really useful and help us moving in the right direction. And you can be sure, there will be still work to do after your graduation! :)

About my workflow... maybe I'm a notification addicted but I like to know when an app is updated from the Play Store. Most of the times I just ignore the pop-up, sometimes I say "oh, they updated Ingress, let me see what's new!"
So, I understand your point, but still think we can have different workflows and we must find a good compromise to improve both our use cases. And I hope 1) and 2) will do it.

There is another thing I'd like: ignoring selectively only "some" notifications from an app. For instance I have many group chats in Hangout or WhatsApp... some of them are important for me when I'm on the desktop, others are not. I know I can mute them on the phone... but maybe I just want to keep the notification on the phone but not forwarding them... or I'd like to mute them all someone sent a message like "Hey @kurt, please have a look!". So... there is definitely more we can do on this... just not enough time :)

The confusion about Linux vs Android apps is real... we'd like to show the HolyLobster logo but I think we were not able to show both the app icon and the Nuntius icon. I'll check with Nacho on the Linux side. Also because... hey! we have a fantastic logo we are proud of... so why hiding it??? :D

I have a spike for Mac which I'm working in the spare time (i.e. never) which shows the notifications with both icons, still not perfect but I think something like this would help on Linux too.

Here is a screenshot on how it looks:
![screen shot 2015-04-22 at 09 23 31](https://cloud.githubusercontent.com/assets/4067807/7269164/7114d1f8-e8d1-11e4-9196-2cbc1ae4e9e4.png)

You see the big icon is the app, the smaller is Nuntius.

Thank you for sharing your thoughts, keep the feedback coming!
Have a nice day!

**Comment by Hefting** [comment]
Hi Andrea,

Thank you for your reply! It sounds like you have a lot of great ideas about forwarding notifications in a smarter way, which sound all very good. And the filtering of notifications within an application is also an interesting one. Lots of things to keep in mind.

About the icons: of course you want to show the Holy Lobster... I mean: maybe we could start our own religion, haha! ;-) Just kidding, but I do understand that it might be a problem to show both. The next question I would ask is: do you have to show them both? On the one side I would say: in the screenshot the *little* lobster makes sure that you know it's the gReader Pro on your phone, not on your desktop. On the other hand I would say: not every notification system might be able to show an extra little icon and things could get confusing if there are two equally sized icons in it. So yeah, like you said: maybe only show the lobster and then the name of the app in the title notification? I'm not sure...

Do you also send the icon via Bluetooth? If so, maybe you could merge them together in one image and save it in a cache for later uses. This also allows for applying a standard style: make the application icon always greyscale and add a colored lobster to it. Or the other way around if you want to focus on the application and just add the lobster for clarification it's from the phone. I'm just brainstorming, but I haven't tested it, so it could also look dirty - two logo's in one small image.

Good luck! Looking forward to see more features of the app.

Cheers, Ties Jan
